### ISSUE TITLE
chromium 79 won't open cpuprofile

### ISSUE THREAD

**Issue by ygrek** [copy/gdbprofiler#10]
F12 - Performance - Load profile : loads the file but nothing shown. 

https://stackoverflow.com/a/41291519 hints that json format might have changed

**Comment by copy** [comment]
It needs to be loaded in the JavaScript profiler tab, which is hidden behind the ... menu -> More Tools. As of Chromium 80 this still works for me.

I'll leave this issue open to update docs and maybe update the json format to the one accepted by the performance tools.

**Comment by ygrek** [comment]
Oh, I didn't know about that. Thanks. Works indeed.
