### ISSUE TITLE
This tool works on windows wsl2 and macOS 12.

### ISSUE THREAD

**Issue by arbipher** [copy/gdbprofiler#11]
It is not really an issue but I want to share if people are wondering whether this tool works on other platforms other than real linux.

I test it under OCaml 4.14.0.

### wsl2 (work)
For ubuntu 20.04 on windows wsl2, just follow the instructions in `Readme.md`. 

### mac + lldb (work)
For macOS 12, I build `lldb-mi` from the [source](https://github.com/lldb-tools/lldb-mi). I follow the instructions in section Building against custom LLDB with llvm installed from homebrew:

```
cmake . -DLLVM_DIR=/usr/local/opt/llvm/lib/cmake/llvm
cmake --build .
```

Then I change the command a bit:

```
gdbprofiler -p `pgrep my_example_program.native` --cpuprofile example.cpuprofile --callgrind callgrind.out --use-lldb
```

### mac + gdb (not work)

I don't figure out how to use `gdb` mode on mac.

I installed `gdb` from homebrew and followed the [certificate signing](https://sourceware.org/gdb/wiki/PermissionsDarwin) suggested in the brew installation log. After doing the manual steps, I can enter the normal `gdb`.
However, when running `gdbprofiler`, my program always exits immediately. I _guess_ there may be some interrupt.

(since mac+llvm works, I don't delve into it)

**Comment by copy** [comment]
Thanks for letting me know!

I mostly prefer perf over gdbprofiler these days (see [this thread](https://discuss.ocaml.org/t/ann-perf-demangling-of-ocaml-symbols-a-short-introduction-to-perf/7143)), since it has much less overhead. perf should also work on wsl2, but not on Macs.

**Comment by arbipher** [comment]
I see! I am attempting several OCaml profiling tools recently. `perf` looks good to me. Thanks for sharing the link.
