### ISSUE TITLE
does not produce a .cpuprofile file compatible with current tools

### ISSUE THREAD

**Issue by medovina** [copy/gdbprofiler#13]
I'm running gdbprofiler with OCaml 5.1.1 on Ubuntu 24.04.

gdbprofiler does not seem to produce a .cpuprofile file that is compatible with current tools.  For example, I used it to profile the attached file hello.ml.  It produced the attached file out.cpuprofile.  I'm not able to open this file in the Visual Studio Code cpuprofile view, or in Chromium's developer tools, or in an online cpuprofile viewer (https://lahmatiy.github.io/cpupro/).

[hello.ml](https://github.com/copy/gdbprofiler/files/15317087/hello_ml.txt)
[out.cpuprofile](https://github.com/copy/gdbprofiler/files/15317084/out.cpuprofile)

**Comment by copy** [comment]
Yeah, the old profiler in devtools that was using .cpuprofile was already deprecated for a while, apparently it's gone now. I'm not sure why the web viewer doesn't work.

That said, I wouldn't recommend using gdbprofiler, as it has a high overhead. These days I use [perf](https://discuss.ocaml.org/t/ann-perf-demangling-of-ocaml-symbols-a-short-introduction-to-perf/7143), usually with [samply](https://github.com/mstange/samply/) (samply also has macOS support).
