### ISSUE TITLE
Support for >4.06?

### ISSUE THREAD

**Issue by rgrinberg** [copy/gdbprofiler#9]
The readme mentions that OCaml is supported up to 4.06. Is there a reason why this project can't be made to work on later versions?

**Comment by ygrek** [comment]
it builds fine with current OCaml

**Comment by copy** [comment]
Yep, builds and works on OCaml 4.10. I'll update the readme.

I tend to use `perf` these days, since it has a lower overhead and works just fine on OCaml binaries. A perf.data to cpuprofile converter with OCaml demangling also has been on my todo list for years, but you know how it is.
